apiVersion: v1
kind: Pod
metadata:
  name: phpfpm-nginx
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    
    - name: nginx-config-volume
      configMap:
        name: nginx-config

  containers:
    - image: wfsilva/phpfpm-demo:v1
      imagePullPolicy: Always
      name: php
      volumeMounts:
        - name: shared-files
          mountPath: /app
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /src/. /app/"]
    
    - image: nginx:alpine
      imagePullPolicy: Always
      name: nginx
      volumeMounts:
        - name: shared-files
          mountPath: /app
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
