---
apiVersion: v1
kind: Pod
metadata:
  name: podaffinity
spec:
  containers:
  - name: demoapp
    image: wfsilva/demoapp:v3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: curso
            operator: In
            values:
            - k8s
        topologyKey: "kubernetes.io/hostname"
