apiVersion: v1
kind: Pod
metadata:
  name: demo-oom
spec:
  containers:
  - name: demo-oom
    image: wfsilva/memalloc
    args: ["512", "512"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"