apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: web
    image: wfsilva/demoapp:v1
  tolerations:
  - key: "doenca"
    operator: "Equal"
    value: "dengue"
    effect: "NoExecute"