apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: demo
    image: wfsilva/demoapp:v1
    resources:
      requests:
        memory: "5Gi"
        cpu: "250m"
      limits:
        memory: "5Gi"
        cpu: "500m"