apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demoapp
  labels:
    app: demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: wfsilva/demoapp:v2
        ports:
        - containerPort: 8080
