apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demoapp
  labels:
    app: demoapp
    tier: web 
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
      - name: demoapp
        image: wfsilva/demoapp:v1

