apiVersion: v1
kind: Pod
metadata:
  name: hungry
spec:
  containers:
  - name: demo
    image: wfsilva/demoapp:v2
    resources:
      requests:
        memory: "64Mi"
        cpu: "2000m"
      limits:
        memory: "128Mi"
        cpu: "4000m"