apiVersion: v1
kind: Pod
metadata:
  name: hungry
spec:
  containers:
  - name: demo
    image: wfsilva/demoapp:v2
    resources:
      requests:
        memory: "64Gi"
        cpu: "32"
      limits:
        memory: "128Gi"
        cpu: "64"
