apiVersion: v1
kind: Pod
metadata:
  name: memory
spec:
  containers:
  - name: memory
    args:
    - "512"
    - "512"
    image: progrium/memalloc
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
