apiVersion: batch/v1
kind: Job
metadata:
  name: job-pinger
spec:
  backoffLimit: 4
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: pinger
        image: alpine
        command: ["ping"]
        args: ["-c","50","8.8.8.8"]
      restartPolicy: OnFailure
