apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
  name: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nfs-pv
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs-pv
        persistentVolumeClaim:
          claimName: nfs-pvc
