apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo
  name: demo
spec:
  containers:
  - image: alpine
    name: demo
    command: ["sleep","3600"]
    volumeMounts:
    - name: nfs-pv
      mountPath: /dados
  volumes:
  - name: nfs-pv
    persistentVolumeClaim:
      claimName: nfs-pvc
