apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
  - name: container-a
    image: busybox
    command: ['sleep','3600']
    volumeMounts:
    - mountPath: /dados
      name: vol-dados
  - name: container-b
    image: alpine
    command: ['sleep','3600']
    volumeMounts:
    - mountPath: /data
      name: vol-dados
  volumes:
  - name: vol-dados
    emptyDir: {}