apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-delete
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /persistence
    server: 192.168.7.10
    readOnly: false