apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-retain
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /persistence
    server: 192.168.7.10
    readOnly: false