apiVersion: v1
kind: Pod
metadata:
  name: cm-file
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep","600"]
    volumeMounts:
      - name: exemplo
        subPath: exemplo-cm.txt
        mountPath: /exemplo-cm.txt
  volumes:
    - name: exemplo
      configMap:
        name: demo-file