apiVersion: v1
kind: Pod
metadata:
  name: cm-literal
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep","600"]
    envFrom:
    - configMapRef:
        name: demo-literal
    env:
      - name: variavel-um
        valueFrom:
          configMapKeyRef:
            name: demo-literal
            key: curso
      - name: variavel-dois
        valueFrom:
          configMapKeyRef:
            name: demo-literal
            key: chave