apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-recreate
  labels:
    app: demoapp
spec:
  strategy:
    type: Recreate
  replicas: 10
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: wfsilva/demoapp:v2
        ports:
        - containerPort: 8080

