apiVersion: v1
kind: Pod
metadata:
  name: demoapp
  labels:
    chave: valor
    app: demoapp
spec:
  containers:
  - name: demoapp
    image: wfsilva/demoapp:v1
    ports:
      - containerPort: 8080
