apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demoapp
spec:
  replicas: 3
  selector:
    app: demoapp
  template:
    metadata:
      name: demoapp
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: wfsilva/demoapp:v1
        ports:
        - containerPort: 8080
