apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep","600"]
    envFrom:
    - secretRef:
        name: cli-literal
    env:
      - name: usuario-file
        valueFrom:
          secretKeyRef:
            name: cli-file
            key: user.txt
      - name: senha-file
        valueFrom:
          secretKeyRef:
            name: cli-file
            key: pass.txt