apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pinger
  labels:
    name: pinger
spec:
  selector:
    matchLabels:
      name: pinger
  template:
    metadata:
      labels:
        name: pinger
    spec:
      nodeSelector:
        curso: k8s
      containers:
      - name: pinger
        image: alpine
        command: 
        - "ping"
        args: 
        - "8.8.8.8"
        
